# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.72.0")

default_platform(:ios)

lane :alpha do
  # build the release variant
  build_ios_app(scheme: "mobileApp", configuration: "Debug", export_method: "enterprise", output_name: "mobileApp.ipa")

  # automatically increment by one
  increment_build_number

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: Centrica Connected Ltd.,
    api_token: "693740bd5b49ee8c3511841a471f34152d96be98",
    build_secret: "23477f34ef5935f66566b52bbbb84f27afb6d31f2468fed7877a57397c5e1ec4",
    notifications: true,
  )
end
