# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.72.0")

default_platform(:android)

lane :alpha do

  # build the release variant
  # build_android_app(task: "assembleDebug")

  # upload to Beta by Crashlytics
  # crashlytics(
  #     api_token: sh("ansible-vault --vault-password-file ../../ansible-vault/bin/get_vault_secret.sh view ../../ansible-vault/crashlytics-secrets.yml | grep crashlytics-api-token | cut -f 2- -d ':' | tr -d '\n'"),
  #     build_secret: sh("ansible-vault --vault-password-file ../../ansible-vault/bin/get_vault_secret.sh view ../../ansible-vault/crashlytics-secrets.yml | grep crashlytics-api-secret | cut -f 2- -d ':' | tr -d '\n'"),
  #     groups: "Alpha_Android"
  #  )

  slack(
    message: "App successfully released to Alpha_Android user group!",
    slack_url: "https://hooks.slack.com/services/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",
    username: "MOBILE-APP-DEMO",
    channel: "#tobedeleeted",
    attachment_properties: {
      fields: [{
        title: "Auto bot check",
        value: "Success",
        short: true
      }]
    }
  )
end
